baseURL = "https://amzrk2.cc"
languageCode = "zh-hans"
title = "DSRCA"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
enableRobotsTXT = true
googleAnalytics = "UA-146011233-1"

[params]
  author = "DSRKafuU"
  description = "DSRCA home project."
  images = ["https://amzrk2.cc/img/og.png"]
