import {
  mdiHome,
  mdiTelevisionBox,
  mdiTelevisionClassic,
  mdiGamepad,
  mdiMinecraft,
  mdiAccountSupervisorCircle,
  mdiInformation,
  mdiTimeline,
  mdiLicense,
  mdiOpenInNew,
  mdiPackageVariantClosed,
  mdiCertificateOutline,
  mdiLinkVariant,
  mdiCheck,
  mdiHistory,
  mdiCopyright,
  mdiAlert,
  mdiStarFace,
} from '@mdi/js';

export {
  mdiHome,
  mdiTelevisionBox,
  mdiTelevisionClassic,
  mdiGamepad,
  mdiMinecraft,
  mdiAccountSupervisorCircle,
  mdiInformation,
  mdiTimeline,
  mdiLicense,
  mdiOpenInNew,
  mdiPackageVariantClosed,
  mdiCertificateOutline,
  mdiLinkVariant,
  mdiCheck,
  mdiHistory,
  mdiCopyright,
  mdiAlert,
  mdiStarFace,
};
