name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node.js
        uses: actions/setup-node@v2.1.3
        with:
          node-version: "14"

      - name: build
        run: |
          npm ci
          npm run build
