# 每天重建站点
name: refresh_meta

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  regenerate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - env:
          CF_HOOK: ${{ secrets.CF_HOOK }}
        run: curl -X POST "$CF_HOOK"
